### ISSUE TITLE
[CLI]: ReferenceError: DOMException is not defined

### ISSUE THREAD

**Issue by daorren** [tacoinfra/tezos-faucet#4]
I'm using 
```
npx @tacoinfra/get-tez tz1aN5YUEeYoyvu5HwMquyLZ3fynWaSFou8u --amount 500 --network ghostnet
```
as suggested from https://faucet.ghostnet.teztnets.com/
but I get this output
```
get-tez v1.0.8 - Get Free Tez

(node:97019) UnhandledPromiseRejectionWarning: ReferenceError: DOMException is not defined
    at /Users/sh01028ml/.npm/_npx/97019/lib/node_modules/@tacoinfra/get-tez/dist/getTez.js:309:28
    at Generator.throw (<anonymous>)
    at rejected (/Users/sh01028ml/.npm/_npx/97019/lib/node_modules/@tacoinfra/get-tez/dist/getTez.js:7:65)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:97019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:97019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by craigbuckler** [comment]
Please check you're using Node.js version 18 or later (`node -v`).
